/*
 * Mayra Lucero García Ramírez 
 * Victor Adrian Suaréz Ruiz
 */
package pantallas;

import apprestaurant.Restaurante;
import apprestaurant.Usuario;
import apprestaurant.Utilidad;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;


public class MenuPrincipal extends javax.swing.JFrame {
    String correo;
    Usuario actual;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String actual) {
        initComponents();
        ArrayList<Usuario> usuarios = Utilidad.leerUsuarios();
        correo = actual;
        this.actual = Utilidad.buscarUsuario(usuarios, actual);
        listaRestaurantes.setVisible(false);
        ir.setVisible(false);
        this.setName("MP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bNuevoRestaurante = new javax.swing.JButton();
        busquedaRest = new javax.swing.JTextField();
        restaurante1 = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        listaRestaurantes = new javax.swing.JScrollPane();
        listaRest = new javax.swing.JList<>();
        ir = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bNuevoRestaurante.setText("Nuevo Restaurante");
        bNuevoRestaurante.setActionCommand("NuevoRestaurante");
        bNuevoRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoRestauranteActionPerformed(evt);
            }
        });
        getContentPane().add(bNuevoRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 40));

        busquedaRest.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        busquedaRest.setText("Restaurante");
        busquedaRest.setMaximumSize(new java.awt.Dimension(20, 46));
        busquedaRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaRestActionPerformed(evt);
            }
        });
        getContentPane().add(busquedaRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 180, 30));

        restaurante1.setText("Restaurantes");
        restaurante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurante1ActionPerformed(evt);
            }
        });
        getContentPane().add(restaurante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 40));

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 70, 29));

        listaRest.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaRestaurantes.setViewportView(listaRest);

        getContentPane().add(listaRestaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 380, 260));

        ir.setText("Ir");
        ir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irActionPerformed(evt);
            }
        });
        getContentPane().add(ir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        Cerrar.setText("Cerrar Sesión");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaRestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaRestActionPerformed

    private void bNuevoRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoRestauranteActionPerformed
        listaRestaurantes.setVisible(false);
        ir.setVisible(false);
        NuevoRestaurante nuevoR = new NuevoRestaurante(correo);
        this.setVisible(false);
        nuevoR.setVisible(true);
    }//GEN-LAST:event_bNuevoRestauranteActionPerformed

    private void restaurante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurante1ActionPerformed
        ArrayList<Restaurante> rests = actual.accedeRestaurantes();
        
        //System.out.println(actual.accedeCorreo());
        DefaultListModel modelo = new DefaultListModel();
        for(Restaurante r: rests)
        {
            System.out.println("   "+r.accedeNombre());
            modelo.addElement(r.accedeNombre());
        }
        
        listaRest.setModel(modelo);
        listaRestaurantes.setVisible(true);
        ir.setVisible(true);
    }//GEN-LAST:event_restaurante1ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String nomRes  = busquedaRest.getText();
        ArrayList<Restaurante> res = new  ArrayList<Restaurante>();
        ArrayList<Usuario> usuarios = Utilidad.leerUsuarios();
        
        for(int i = 0; i<usuarios.size();i++)
        {
            if( usuarios.get(i).buscarRestaurante(nomRes) != null)
            {
                res.add(usuarios.get(i).buscarRestaurante(nomRes));
            }
        }
        DefaultListModel modelo = new DefaultListModel();
        for(Restaurante r: res)
        {
            modelo.addElement(r.accedeNombre());
        }
        
        listaRest.setModel(modelo);
        listaRestaurantes.setVisible(true);
        ir.setVisible(true);
    }//GEN-LAST:event_buscarActionPerformed

    private void irActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irActionPerformed
        if(!listaRest.isSelectionEmpty())
        {
            int i= listaRest.getSelectedIndex();
            DefaultListModel modelo = (DefaultListModel) listaRest.getModel();
            String s = (String) modelo.getElementAt(i);
            MenuRestaurante menuRes = new MenuRestaurante(actual.accedeCorreo(), actual.accedeNomRestaurante(i)); 
            
            this.setVisible(false);
            menuRes.setVisible(true);
            
            listaRestaurantes.setVisible(false);
            ir.setVisible(false);
        }
    }//GEN-LAST:event_irActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        Frame[] frames = Frame.getFrames();
        for(int i=0;i<frames.length;i++)
        {
            if(frames[i].getName().equals("iniciar"))
            {
                this.setVisible(false);
                frames[i].setVisible(true);
            }
        }
    }//GEN-LAST:event_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton bNuevoRestaurante;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField busquedaRest;
    private javax.swing.JButton ir;
    private javax.swing.JList<String> listaRest;
    private javax.swing.JScrollPane listaRestaurantes;
    private javax.swing.JButton restaurante1;
    // End of variables declaration//GEN-END:variables
}
