/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

/**
 *
 * @author lucerogarcia
 */
public class nuevoU extends javax.swing.JInternalFrame {

    /**
     * Creates new form nuevoCocinero
     */
    public nuevoU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnombre = new javax.swing.JLabel();
        lcorreo = new javax.swing.JLabel();
        lHorario = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        horini = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setTitle("Nuevo Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnombre.setBackground(new java.awt.Color(107, 107, 203));
        lnombre.setText("Nombre: ");
        getContentPane().add(lnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 33, -1, -1));

        lcorreo.setText("Correo:");
        getContentPane().add(lcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        lHorario.setText("Horario:");
        getContentPane().add(lHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 60, 20));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 200, -1));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 200, -1));

        horini.setText("inicio");
        getContentPane().add(horini, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 96, 70, 30));

        jLabel1.setText("a");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 20, -1));

        jTextField1.setText("fin");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 96, 60, 30));

        jLabel2.setText("Tipo de Usuario: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocinero", "Empleado", "Mesero" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correo;
    private javax.swing.JTextField horini;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lHorario;
    private javax.swing.JLabel lcorreo;
    private javax.swing.JLabel lnombre;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
