/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

/**
 *
 * @author lucerogarcia
 */
public class Quitar extends javax.swing.JFrame {

    /**
     * Creates new form Quitar
     */
    public Quitar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloEliminarPlatillo = new javax.swing.JLabel();
        listaPlatillosOrden = new javax.swing.JScrollPane();
        listaPlatillos = new javax.swing.JList<>();
        labelPlatillosOrd = new javax.swing.JLabel();
        finQuitar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 359));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloEliminarPlatillo.setFont(new java.awt.Font("PT Mono", 3, 18)); // NOI18N
        tituloEliminarPlatillo.setText("Eliminar Platillo");
        getContentPane().add(tituloEliminarPlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 6, -1, 54));

        listaPlatillos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPlatillosOrden.setViewportView(listaPlatillos);

        getContentPane().add(listaPlatillosOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 290, 260));

        labelPlatillosOrd.setBackground(new java.awt.Color(204, 204, 255));
        labelPlatillosOrd.setText("Lista de Platillos en la orden");
        getContentPane().add(labelPlatillosOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 190, -1));

        finQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        finQuitar.setText("Listo");
        finQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(finQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 97, 29));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 90, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finQuitarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quitar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finQuitar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelPlatillosOrd;
    private javax.swing.JList<String> listaPlatillos;
    private javax.swing.JScrollPane listaPlatillosOrden;
    private javax.swing.JLabel tituloEliminarPlatillo;
    // End of variables declaration//GEN-END:variables
}
